version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.27.1
    - 5.27.2
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: css-loader
    versions:
    - 5.1.3
    - 5.2.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.15
  - dependency-name: cypress
    versions:
    - 6.7.1
    - 7.0.0
    - 7.0.1
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
    - 7.13.14
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.13.0
